### ISSUE TITLE
Recommendations 

### ISSUE THREAD

**Issue by xtraashixx** [arimgibson/Deadname-Remover#157]
hey!!  i recommend addin a feature that replaces pronouns so you can replace she/her with they/them or he/him ect etc! it would be very helpful!

**Comment by AriGibson** [comment]
Hmmmmmm... not sure I'm completely on-board with this suggestion, although I see what you're getting at. I'm just thinking about reading like an article or something, and every person on the page is getting misgendered because the extension is changing _all the pronouns_ opposed to just pronouns that are referring to you
