### ISSUE TITLE
Suggestion for Deadname Remover

### ISSUE THREAD

**Issue by ATU-2004** [arimgibson/Deadname-Remover#22]
A new idea could potentially be to remove and replace misgenders. I've been a little annoyed whenever I see a misgender, and it would be a really nice touch to this already amazing application.

**Comment by arimgibson** [comment]
Sorry for the late follow up! Excuse the brevity and templated replies as I clear through tons of GitHub issues.

Unfortunately this is a really hard feature to implement because it would most likely end up replacing the pronouns of everyone on the page. i.e. if I used pronoun "y", it would replace all pronoun "x" with pronoun "y" even for people who actually use pronoun "x"

Open to suggestions about how to implement this though! Closing for now
