### ISSUE TITLE
Deadname Remover

### ISSUE THREAD

**Issue by ArsonRules123** [arimgibson/Deadname-Remover#410]
Hello so does the name only show up on your screen or does it show up on others? Like if I send a friend a email.

**Comment by arimgibson** [comment]
Unfortunately it only shows up on your screen, and there's really no practical way to make it work on everyone's screen because of how the web works. This extension essentially waits until the page loads on your computer, then does a find and replace on all the page text to swap out your deadname with your chosen name. Wish it was possible to make it work for everyone, but I've also heard of friends installing the extension and plugging in your name!
