### ISSUE TITLE
The greasemonkey files aren't found

### ISSUE THREAD

**Issue by arisu0** [arimgibson/Deadname-Remover#527]
When using in qutebrowser it won't be able to get the require file
![image](https://user-images.githubusercontent.com/39315312/185953652-5f0d14c1-fa87-4416-828c-adf5259e6923.png)

Even on the readme, the part of the greasemonkey install link it will lead to a not found page
![image](https://user-images.githubusercontent.com/39315312/185953865-ce5b15b9-4acd-4616-a3e2-52f17342c78a.png)

**Comment by arimgibson** [comment]
Hi @arisu0 !

Is there a specific part of the code that had that link? The issue here is that the default branch for the repository was renamed from `master` to `main` (see [why GitHub recommends this](https://github.com/github/renaming)). I'd love to correct that link if it's occuring somewhere.

Otherwise, on your side, just replace where the link says `master` with the word `main`. Let me know if that doesn't do it!

**Comment by arimgibson** [comment]
Thanks for letting me know; updated all those references :)
